### ISSUE TITLE
"Unable to discover device type" restoring iPhone8,2

### ISSUE THREAD

**Issue by SebastianBar** [libimobiledevice/idevicerestore#97] opened 2016-04-11 21:33 UTC
Hello! I'm having that issue. I've seen a similar question but asking for iPhone SE, I've checked the libirecovery/src/libirecovery.c file and it already has data for iPhone 8,2. And yep, I can get info from ideviceinfo while on normal mode.

EDIT: I believe I'm using an older libirecovery.dll file, is there any link to get the latest compiled file? Because the binaries from the main website, it seems that are outdated from the github ones :(

**Comment by nikias** [comment] 2016-04-12 10:35
There are no official binaries. Compile your own from https://github.com/libimobiledevice/libirecovery.git . Closing since this is not a bug.

**Closed by nikias** 2016-04-12 10:35 UTC
