### ISSUE TITLE
Sending IBEC freezes

### ISSUE THREAD

**Issue by alexxgarci** [libimobiledevice/idevicerestore#103] opened 2016-05-19 09:02 UTC
NOTE: using cached version data
Found device in DFU mode
Identified device as iPhone6,1
Extracting BuildManifest from IPSW
Product Version: 9.3.1
Product Build: 13E238 Major: 13
Device supports Image4: true
Variant: Customer Erase Install (IPSW)
This restore will erase your device data.
Found ECID 2979855625828
Getting ApNonce in dfu mode... 1d ed f2 88 af ea 58 8e 80 3b e0 73 7a f7 ae 5c a8 7d 10 7f 
Trying to fetch new SHSH blob
Getting SepNonce in dfu mode... da 2c a1 4b 60 66 c0 2b 6f 3c d9 2c ac ef d6 d2 59 63 fa 39 
WARNING: Unable to find BbSkeyId node
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
Received SHSH blobs
Extracting filesystem from IPSW
[==================================================] 100.0%
Extracting iBSS.n51.RELEASE.im4p...
Sending iBSS (140333 bytes)...
[==================================================] 100.0%
Nonce: 1d ed f2 88 af ea 58 8e 80 3b e0 73 7a f7 ae 5c a8 7d 10 7f 
Extracting iBEC.n51.RELEASE.im4p...
Sending iBEC (652333 bytes)...
[=========================================         ]  80.4%

I'm using OSX 10.11.4 and an iPhone 5s. The process freezes at this point and nothing happens. Any help?

**Comment by nikias** [comment] 2016-05-19 10:39
Duplicate of #75

**Closed by nikias** 2016-05-19 10:39 UTC
Labels: duplicate
